{ imports, pkgs, ... }:

{
  imports = [
    ./hyprlock.nix
    ./hyprpaper.nix
    ./noctalia.nix
  ];

  home.packages = with pkgs; [
    brightnessctl
    hyprlauncher
    hyprpaper
    kdePackages.dolphin
    playerctl
    rofi
    waypaper
  ];

  wayland.windowManager.hyprland = {
    enable = true;
    systemd.enable = false;
    configType = "lua";

    extraConfig = ''
      local mod = "ALT"
      local ipc = "noctalia-shell ipc call"
      local accent   = "0xffcba6f7"
      local surface1 = "0xff45475a"
      local surface0 = "0xff313244"
      local crust    = "0xff11111b"

      -- Autostart
      hl.on("hyprland.start", function()
        hl.exec_cmd("hyprpaper &")
        hl.exec_cmd("openrazer")
        hl.exec_cmd("noctalia-shell &")
        hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
      end)

      -- Variables d'environnement
      hl.env("XCURSOR_SIZE", "24")

      -- Paramètres principaux
      hl.config({
        autogenerated = false,
        general = {
          ["col.active_border"] = accent,
          ["col.inactive_border"] = surface0,
          resize_on_border = false,
          border_size = 2
        },
        decoration = {
          rounding = 10,
          active_opacity = 1,
          inactive_opacity = 0.8,
          shadow = {
            enabled = true,
            range = 15,
            render_power = 3,
            color = crust
          },
          blur = {
            enabled = true,
            size = 4,
            passes = 2,
            new_optimizations = true,
            ignore_opacity = true
          }
        },
        animations = {
          enabled = true,
          bezier = {
            { "easeOutQuint", 0.23, 1, 0.32, 1 },
            { "easeInOutCubic", 0.65, 0.05, 0.36, 1 },
            { "linear", 0, 0, 1, 1 },
            { "almostLinear", 0.5, 0.5, 0.75, 1 },
            { "quick", 0.15, 0, 0.1, 1 }
          },
          animation = {
            { "global", 1, 10, "default" },
            { "border", 1, 5.39, "easeOutQuint" },
            { "windows", 1, 4.79, "easeOutQuint" },
            { "windowsIn", 1, 4.1, "easeOutQuint", "popin 87%" },
            { "windowsOut", 1, 1.49, "linear", "popin 87%" },
            { "fadeIn", 1, 1.73, "almostLinear" },
            { "fadeOut", 1, 1.46, "almostLinear" },
            { "fade", 1, 3.03, "quick" },
            { "layers", 1, 3.81, "easeOutQuint" },
            { "layersIn", 1, 4, "easeOutQuint", "fade" },
            { "layersOut", 1, 1.5, "linear", "fade" },
            { "fadeLayersIn", 1, 1.79, "almostLinear" },
            { "fadeLayersOut", 1, 1.39, "almostLinear" },
            { "workspaces", 1, 1.94, "almostLinear", "fade" },
            { "workspacesIn", 1, 1.21, "almostLinear", "fade" },
            { "workspacesOut", 1, 1.94, "almostLinear", "fade" },
            { "zoomFactor", 1, 7, "quick" }
          }
        },
        source = {
          "~/.config/hypr/monitors.conf"
        },
        misc = {
          disable_hyprland_logo = true,
          disable_splash_rendering = true,
          middle_click_paste = true
        },
        input = {
          kb_layout = "fr",
          kb_variant = "",
          kb_model = "",
          kb_options = "",
          kb_rules = "",
          follow_mouse = 0,
          accel_profile = "flat",
          sensitivity = 0
        }
      })

      -- Raccourcis divers (bind)
      hl.bind(mod .. " + D", hl.dsp.exec_cmd(ipc .. " launcher toggle"))
      hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd(ipc .. " launcher toggle"), { release = true })
      hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd("ghostty"))
      hl.bind(mod .. " + F", hl.dsp.window.fullscreen({ action = "toggle" }))
      hl.bind(mod .. " + A", hl.dsp.window.close())
      hl.bind(mod .. " + E", hl.dsp.exec_cmd("dolphin"))
      hl.bind(mod .. " + V", hl.dsp.window.float({ action = "toggle" }))
      hl.bind(mod .. " + L", hl.dsp.exec_cmd(ipc .. " lockScreen lock"))

      -- Screenshots
      hl.bind("Print", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | wl-copy]]))
      hl.bind("SHIFT + Print", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | swappy -f -]]))
      hl.bind("CTRL + Print", hl.dsp.exec_cmd([[grim ~/Pictures/$(date +'%Y-%m-%d_%Hh%Mm%Ss_screenshot.png')]]))

      -- Gestion des fenêtres
      hl.bind(mod .. " + left", hl.dsp.focus({ direction = "l" }))
      hl.bind(mod .. " + right", hl.dsp.focus({ direction = "r" }))
      hl.bind(mod .. " + up", hl.dsp.focus({ direction = "u" }))
      hl.bind(mod .. " + down", hl.dsp.focus({ direction = "d" }))

      hl.bind(mod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
      hl.bind(mod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
      hl.bind(mod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
      hl.bind(mod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

      -- Espaces de travail (Workspaces)
      local workspaces = {
        {"ampersand", "1"}, {"eacute", "2"}, {"quotedbl", "3"}, {"apostrophe", "4"},
        {"parenleft", "5"}, {"minus", "6"}, {"egrave", "7"}, {"underscore", "8"},
        {"ccedilla", "9"}, {"agrave", "10"}
      }
      for _, ws in ipairs(workspaces) do
        hl.bind(mod .. " + " .. ws[1], hl.dsp.focus({ workspace = ws[2] }))
        hl.bind(mod .. " + SHIFT + " .. ws[1], hl.dsp.window.move({ workspace = ws[2] }))
      end

      -- Raccourcis Souris
      hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
      hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
      hl.bind("mouse:274", hl.dsp.exec_cmd("sh -c 'wl-paste -p | wtype -'"))

      -- Raccourcis Multimédia et Luminosité
      local flag_el = { repeating = true, locked = true }
      local flag_l = { locked = true }

      hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), flag_el)
      hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), flag_el)
      hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), flag_el)
      hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), flag_el)
      hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), flag_el)
      hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), flag_el)

      hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), flag_l)
      hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), flag_l)
      hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), flag_l)
      hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), flag_l)
    '';
  };
}
